StudentViewerWebApp/Models/Assignment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentViewerWebApp.Models
{
    public class Assignment
    {
        public string AssignmentName { get; set; }
        public DateTime DueDate { get; set; }
        public int MaxScore { get; set; }
        public DateTime? CompletionDate { get; set; }
        public int ScoreEarned { get; set; }
    }
}

StudentViewerWebApp/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentViewerWebApp.Models
{
    public class Enrollment
    {
        public DateTime EntryDate { get; set; }
        public DateTime ExitDate { get; set; }
        public string ExitReason { get; set; }
    }
}

StudentViewerWebApp/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentViewerWebApp.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Grade { get; set; }
        public string SchoolName { get; set; }
    }
}

StudentViewerWebApp/Controllers/AssignmentController.cs
using StudentViewerWebApp.Services;
using System.Web.Mvc;

namespace StudentViewerWebApp.Controllers
{
    public class AssignmentController : Controller
    {
        private IStudentService studentService;
        public AssignmentController(IStudentService studentService)
        {
            this.studentService = studentService;
        }
        // GET: Assignment
        public ActionResult Index(int studentId)
        {
            return View(studentId);
        }

        public JsonResult GetStudentAssignments(int studentId)
        {
            var assignments = studentService.GetStudentAssignments(studentId);
            return Json(assignments, JsonRequestBehavior.AllowGet);
        }
    }
}

StudentViewerWebApp/Controllers/EnrollmentController.cs
using StudentViewerWebApp.Services;
using System.Web.Mvc;

namespace StudentViewerWebApp.Controllers
{
    public class EnrollmentController : Controller
    {
        private IStudentService studentService;
        public EnrollmentController(IStudentService studentService)
        {
            this.studentService = studentService;
        }
        public ActionResult Index(int studentId)
        {
            return View(studentId);
        }

        public JsonResult GetStudentEnrollments(int studentId)
        {
            var enrollments = studentService.GetStudentEnrollments(studentId);
            return Json(enrollments, JsonRequestBehavior.AllowGet);
        }
    }
}

StudentViewerWebApp/Controllers/HomeController.cs
using StudentViewerWebApp.Services;
using System.Web.Mvc;

namespace StudentViewerWebApp.Controllers
{
    public class HomeController : Controller
    {
        private IStudentService studentService;
        public HomeController(IStudentService studentService)
        {
            this.studentService = studentService;
        }
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to Student Viewer.";

            return View();
        }
        public JsonResult GetAllStudents()
        {
            var students = studentService.GetAllStudents();
            return Json(students, JsonRequestBehavior.AllowGet);
        }
    }
}

StudentViewerWebApp/Views/Assignment/Index.cshtml
@model int
@{
    ViewBag.Title = "Assignments";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var studentId = Url.RequestContext.RouteData.Values["studentId"];
}

<script src="~/Scripts/Custom/assignment.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        var getStudentAssignmentsUrl = '@Url.Action("GetStudentAssignments",new { studentId=Model})';
        assignmentProvider.getStudentAssignments(getStudentAssignmentsUrl);
    });
</script>

<div class="row">
    <div class="col-lg-12">
        <br />
        <h3>Student Assignments</h3>
        <br />
        <table class="table table-striped table-hover" id="assignmentsList">
            <thead>
                <tr>
                    <th>Assignment Name</th>
                    <th>Due Date</th>
                    <th>Max Score</th>
                    <th>Completion Date</th>
                    <th>Score Earned</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

StudentViewerWebApp/Views/Enrollment/Index.cshtml
@model int
@{
    ViewBag.Title = "Enrollments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Custom/enrollment.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        var getStudentEnrollmentsUrl = '@Url.Action("GetStudentEnrollments",new { studentId = Model})';
        enrollmentProvider.getStudentEnrollments(getStudentEnrollmentsUrl);
    });
</script>

<div class="row">
    <div class="col-lg-12">
        <br />
        <h3>Student Enrollments</h3>
        <br />
        <table class="table table-striped table-hover" id="enrollmentsList">
            <thead>
                <tr>
                    <th>Entry Date</th>
                    <th>Exit Date</th>
                    <th>Exit Reason</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

StudentViewerWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

StudentViewerWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

StudentViewerWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Student Dashboard";
}

<script src="~/Scripts/Custom/index.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        indexProvider.AssignmentUrl = '@Html.ActionLink("Assignments", "Index", "Assignment", new { studentId = "_studentId" }, null)';
        indexProvider.EnrollmentUrl = '@Html.ActionLink("Enrollments", "Index", "Enrollment", new { studentId = "_studentId" }, null)';
        var getAllStudentsUrl = '@Url.Action("GetAllStudents", "Home")';
        indexProvider.getAllStudents(getAllStudentsUrl);
    });
</script>

<div class="row">
    <div class="col-lg-12">
        <br />
        <h3>Students List</h3>
        <br />
        <table class="table table-striped table-hover" id="studentList">
            <thead>
                <tr>
                    <th>Student Id</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Grade</th>
                    <th>School Name</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

StudentViewerWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Student Viewer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>